skip_welcome_message = true
prompt = "starship prompt"
startup = ["def new-agent [] { ssh-agent -s | lines | split column ';' | where Column2 != '' | get Column1 | each { split column '=' name value }}", "def ssh-agent [] { let count = (ps | where name == 'ssh-agent' | length); if $count == 0 { new-agent } { }}", "ssh-agent | load-env"]
table_mode = "rounded"
max_history_size = 1000000
