skip_welcome_message = true
prompt = "starship prompt"
startup = [
  "gpg-connect-agent /bye",
  "[[name, value]; ['GPG_TTY', (tty)] ['SSH_AUTH_SOCK', '/run/user/1000/gnupg/S.gpg-agent.ssh']] | load-env",
  "alias gg = lazygit"
]
table_mode = "rounded"
max_history_size = 1000000
