theme = "native"
icons = "awesome"

[[block]]
block = "notify"

[[block]]
block = "custom"
command = '~/.scripts/mute-status.sh'
on_click = "pactl set-source-volume @DEFAULT_SOURCE@ 55000 && pactl set-source-mute @DEFAULT_SOURCE@ toggle"
json = true
interval = 1

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {barchart}"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

#[[block]]
#block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

