[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.php]
filetypes = ["php"]
roots = ["composer.json"]
command = "npx"
args = ["intelephense"]

#[language.deno]
#filetypes = ["typescript", "javascript"]
#roots = [".git"]
#command = "deno"
#args = ["lsp", "--unstable"]

#[language.deno.initialization_options]
#enable = true
#lint = true

#[language.typescript]
#filetypes = ["typescript"]
#roots = ["package.json"]
#command = "typescript-language-server"
#args = ["--stdio"]

[language.tsx]
filetypes = ["typescript"]
roots = ["package.json"]
command = "npx"
args = ["typescript-language-server", "--stdio"]

