[language.php]
filetypes = ["php"]
roots = ["composer.json"]
command = "node"
args = ["/home/louis/.nvm/versions/node/v11.15.0/bin/intelephense"]

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

#[language.typescript]
#filetypes = ["typescript"]
#roots = ["package.json", "tsconfig.json"]
#command = "javascript-typescript-stdio"
