[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.php]
filetypes = ["php"]
roots = ["composer.json"]
command = "node"
args = ["/home/louis/.nvm/versions/node/v11.15.0/bin/intelephense"]

#[language.deno]
#filetypes = ["typescript", "javascript"]
#roots = [".git"]
#command = "deno"
#args = ["lsp", "--unstable"]

#[language.deno.initialization_options]
#enable = true
#lint = true

#[language.typescript]
#filetypes = ["typescript"]
#roots = ["package.json"]
#command = "typescript-language-server"
#args = ["--stdio"]

[language.tsx]
filetypes = ["typescript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

#[language.typescript]
#filetypes = ["typescript"]
#roots = ["package.json", "tsconfig.json"]
#command = "javascript-typescript-stdio"
