[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.php]
filetypes = ["php"]
roots = ["composer.json"]
command = "npx"
args = ["intelephense"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".ccls", ".git"]
command = "clangd"
#args = ["-log=verbose"]

#[language.typescript]
#filetypes = ["typescript", "javascript"]
#roots = [".git"]
#command = "deno"
#args = ["lsp"]

#[language.typescript.settings.initialization_options]
#enable = true
#lint = true

#[language.typescript]
#filetypes = ["typescript"]
#roots = ["package.json"]
#command = "typescript-language-server"
#args = ["--stdio"]

[language.tsx]
filetypes = ["typescript"]
roots = [".git", "package.json"]
command = "npx"
args = ["typescript-language-server", "--stdio"]

